### PR TITLE
Fix/margin styles

### LINKED ISSUE #30: Have a tiny padding on the right too (remove  hb--mr-2 ?)
Hi,

https://github.com/ReeceM/h-bar/blob/a5c91e33d6589215af48388467840dc5edaac79c/src/banner/banner.js#L97

By default, the bar looks like this on a small screen:
Screenshot from 2022-12-21 11-49-29

When disabling `hb--mr-2`, it fixes the display to have a tiny padding on the right too 
```
.hb--mr-2 {
    /* margin-right: -0.5rem; */
}
```
Screenshot from 2022-12-21 11-49-34

Maybe that class shouldn't be added?

### PR DESCRIPTION
**Pull request by ReeceM**

### CODE REVIEW

File: src/banner/styling.js [hunk 1]
```diff
@@ -8,7 +8,7 @@
 export const styling = {
     wrapper: "hb-flex hb-w-full hd-flex-col md:hb-flex-row hb-text-sm hb-py-2 md:hb-px-20 hb-px-1 hb-items-center hb-justify-between",
     linkWrapper: "hb-flex hb-items-center",
-    badge: "hb-px-2 hb-mx-2 hb-leading-relaxed hb-tracking-wider hb-uppercase hb-font-semibold hb-rounded-full hb-text-xs",
+    badge: "hb-px-2 hb-mr-2 hb-leading-relaxed hb-tracking-wider hb-uppercase hb-font-semibold hb-rounded-full hb-text-xs",
```
Comment (ReeceM) [inline src/banner/styling.js:11]: This is to remove the extra margin on the left too so it's balanced.
